import re

with open(r'E:\Trabajo\1-OpenCode\web-page\curso\index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# The new transcripts from faster-whisper
new_transcripts = {
    'm1-intro': [
        (0.1835, 'Módulo 1. El POT. Nuestra principal hoja de ruta para la planificación del territorio. Bienvenidas y bienvenidos al primer módulo de este curso corto en comprensión del riesgo. Este módulo tiene como objetivo reconocer los elementos principales del plan de ordenamiento territorial y su modelo de ocupación.'),
        (0.1560, 'Esto es fundamental pues toda ciudad necesita organizarse para decidir cómo crecer, qué sonas proteger, dónde construir vivienda, cómo mejorar los barrios, dónde ubicar equipamientos, cómo cuidar las quebradas, las laderas, los cerros y el suelo rural.'),
        (0.1743, 'El POT es la herramienta que orienta el desarrollo físico, ambiental, social y económico del territorio. En palabras sencillas es como una hoja de ruta que le dice a la ciudad. Aquí se puede crecer, aquí se debe mejorar, aquí se debe proteger y aquí no se debe ocupar por razones ambientales o de riesgo.'),
        (0.1743, 'Dentro del POT hay una idea clave, el modelo de ocupación. El modelo de ocupación es la imagen de ciudad que se quiere construir hacia el futuro. Define cómo debe organizarse Medellín, una ciudad más compacta, conectada, con varios centros, con mejores servicios, cerca de los barrios,'),
        (0.1743, 'y con mayor cuidado de sus laderas, quebradas, cerros, río y zonas rurales. Comprender el POT y el modelo de ocupación nos ayuda a entender por qué algunas decisiones sobrevivienda, riesgo, ambiente, movilidad y espacio público son tan importantes para la vida cotidiana.'),
        (0.1376, 'Porque ordenar el territorio no es solo hacer mapas o normas, es decidir cómo queremos vivir y cómo podemos construir una ciudad más segura, justa y sostenible.'),
    ],
    'm2-intro': [
        (0.0586, 'Módulo 2. Entender el territorio donde vivimos. Bienvenidas y bienvenidos al segundo módulo de este curso corto en comprensión del riesgo.'),
        (0.0903, 'Este módulo tiene como objetivo reconocer qué es el borde urbano rural y por qué allí se concentran decisiones claves sobre riesgo, vivienda, ambiente y calidad de vida. Cuando hablamos del borde urbano rural, nos referimos a una zona viva en transformación'),
        (0.0552, 'que conjuga dos dinámicas generales que interactúan. Las ruralidades o formas rurales de evitar y la urbanización. El borde urbano rural es una zona de transición'),
        (0.0854, 'entre el campo y la ciudad. Por ello es necesario una planificación y gestión diferenciada, pues se combina riesgo, híbitad, formas de evitar, soporte urbano, ecosistemas estratégicos, protección del patrimonio y producción rural.'),
        (0.0987, 'En esencia es necesario planificar las formas de ocupar el suelo y las decisiones sobre cómo crece la ciudad. Por este tipo de razones se considera un área de intervención estratégica. En estos territorios se concentran muchas preguntas importantes. ¿Qué tiene que ver esta unidad de planificación'),
        (0.0893, 'con mi vivienda y mi híbitad? ¿Cuáles son las causas principales de las emergencias o desastres en el territorio? ¿Cuáles son los impedimentos para la baja ejecución del mejoramiento integral? Para comprender el riesgo es necesario conocer el territorio,'),
        (0.1030, 'pero también saber diferenciar cuatro ideas básicas. La amenaza es un fenómeno que puede causar daño como un movimiento en masa, una avenida torrencial o una inundación. La exposición se refiere a las personas, viviendas, vías o equipamientos que están ubicados en una zona'),
        (0.0979, 'donde puede ocurrir esa amenaza. La vulnerabilidad tiene que ver con qué tan frágiles o preparados estamos frente a ese posible daño. Y el riesgo aparece cuando se combinan amenaza, exposición y vulnerabilidad. Muchos de nosotros hemos convivido con el riesgo'),
        (0.1002, 'como única alternativa para evitar la ciudad. Pero al ser ciudadanos y ciudadanas significa que no debemos acostumbrarnos a él ni aceptarlo como algo normal. Significa reconocerlo, hablarlo, entenderlo y participar en las decisiones que pueden reducirlo.'),
        (0.1036, 'No sólo necesitamos saber de estudios de riesgo, necesitamos conocer el plan de ordenamiento territorial e incidir en su construcción y actualización. Hoy, además, el cambio climático y la variabilidad climática hacen que las lluvias intensas, los periodos secos y los cambios en el clima se sientan con más fuerza'),
        (0.0760, 'en la vida diaria. Por eso, comprender el territorio es también comprender cómo cuidarnos mejor. Este módulo nos invita a mirar el lugar que habitamos con otros ojos. No sólo como un barrio o una ladera,'),
        (0.0418, 'sino como un territorio con historia, naturaleza, riesgos, capacidades y decisiones compartidas.'),
    ],
    'm2-burnor': [
        (0.0737, '¿Qué es el borde urbano rural y por qué es tan importante? Cuando hablamos del borde urbano rural, muchas veces imaginamos una línea que separa la ciudad del campo, pero en realidad no es solo eso. El borde urbano rural es un territorio de transición, un espacio donde se encuentran y se mezclan distintas formas de evitar,'),
        (0.0421, 'producir, moverse y relacionarse con la naturaleza. Allí habita el obrero, el campesino, la mujer cabeza de hogar, población indígena, afro,'),
        (0.0667, 'el migrante y el desplazado. En ocasiones, un mismo habitante reúne varias de estas condiciones, mujer desplazada por la violencia. Ama de casa afro descendiente, lideresa campesina que ha luchado por los derechos a la vivienda y el híbita digno.'),
        (0.0421, 'En su borde urbano de ese complejo territorio identificamos caminos, senderos, escaleras, pequeños cultivos, huertas caseras y viviendas en distintas etapas de consolidación,'),
        (0.0632, 'que demuestran la existencia de una comunidad que solo busca la permanencia digna. También se evidencia en equipamientos e infraestructura que hablan de una institucionalidad que está llegando, pero requiere mayor presencia. En su borde rural, es más notorio las zonas de protección ambiental,'),
        (0.0737, 'zonas arqueológicas, algunas zonas de cultivo, viviendas campestres y campesinas, los cerros tutelares e inicia la formación de pequeños cuerpos de agua que poco a poco se convierten en quebradas. En estos borde también se evidencia en tensiones muy fuertes, entre crecimiento urbano, control territorial de grupos delincuenciales,'),
        (0.0421, 'conservación y la permanencia de las comunidades. Esta permanencia está asociada a las zonas de alto riesgo, no mitigable y las zonas de protección de ecosistemas estratégicos'),
        (0.0632, 'o retiros de quebradas. El pote de Medellín reconoce que este territorio no puede tratarse como un vacío disponible para seguir construyendo. Por el contrario, lo ubica dentro de las áreas estratégicas de planificación y lo relaciona con varios componentes del ordenamiento territorial.'),
        (0.0702, 'La clasificación del suelo, la estructura ecológica, las áreas de amenaza y riesgo, el sistema público y colectivo y el sistema de ocupación. Eso significa que el borde no se ordena únicamente con normas de construcción. También se ordena con decisiones sobre espacio público, movilidad, equipamientos, gestión del riesgo,'),
        (0.0737, 'protección ambiental en armonía con los principios y disposiciones de la política de protección amoradores y actividades económicas y productivas. El borde urbano rural se ordena con su gente y su secosistemas. Ahora, para los habitantes, se vive en barrios de ladera que aún requieren mejorar distintos aspectos asociados a la vivienda'),
        (0.0526, 'y el híbitat dignos, como el acceso a servicios públicos, regularización y titulación de precios y viviendas, mejor cobertura en educación y salud y la configuración de espacios de encuentro denominado espacio público. Para la administración y planificación territorial,'),
        (0.0632, 'estas son problemáticas comunes que se pueden agrupar en un territorio mayor que también tiene unas condiciones para su desarrollo y así gestionarlo de manera integral. En los documentos de revisión de mediano plazo del pot, esta idea se vuelve todavía más precisa. allí se plantea que el borde urbano rural debe ordenarse como un patrimonio colectivo.'),
        (0.0702, 'Se propone estabilizar su ocupación, prevenir procesos de organización en condiciones de riesgo o degradación ambiental, orientar el crecimiento hacia zonas con mayor capacidad de soporte y articular la estructura ecológica con sistemas productivos rurales. En otras palabras, el borde no es el lugar donde la ciudad termina. Es uno de los lugares donde más claramente se define que tipo de ciudad quiere ser medellín.'),
        (0.0807, 'Las palabras que más resuenan son ciudad incluyente, diversa, adaptada al cambio climático, justa y digna para todas y todos sus habitantes. Y esto tiene una consecuencia muy importante para la ciudadanía. Hablar del borde no es sólo hablar de mapas o de límites administrativos. Es hablar de calidad de vida, de seguridad territorial, de permanencia digna,'),
        (0.0421, 'de acceso a servicios y espacio público, y también de la relación entre la ciudad y su entorno natural. Por eso, entender el borde urbano rural es entender un territorio donde se juega'),
        (0.0805, 'buena parte del equilibrio futuro de Medellín. Repara un café y reflexiona sobre esta frase. El borde urbano rural no es una frontera. Es un territorio clave para pensar el futuro sostenible de Medellín. Quienes lo habitan tienen saberes, experiencias y propuestas indispensables que aportan en la planificación de la ciudad.'),
    ],
    'm2-eep': [
        (0.0546, 'La estructura ecológica de Medellín. Cuando pensamos en Medellín, muchas veces imaginamos un gran valle urbanizado con el río aburrá que lo atraviesa o las montañas que rodean la ciudad. Pero Medellín también tiene una red natural'),
        (0.0717, 'que sostiene la vida, quebradas, cerros, zonas verdes, áreas protegidas, corredores ecológicos y espacios que permiten que el agua, la vegetación, los animales y las personas puedan coexistir. A esta red se le conoce como estructura ecológica. La estructura ecológica de Medellín'),
        (0.0683, 'puede entenderse como un sistema de áreas conectadas que tienen un alto valor ambiental. Su función es mantener procesos ecológicos esenciales y ofrecer beneficios para la vida cotidiana como regulación del agua, protección del suelo, biodiversidad, aire limpio, paisaje, alimentos, espacios'),
        (0.0614, 'de encuentro y bienestar. Además, esta estructura no funciona de manera aislada. Se conecta con la estructura ecológica regional y aporta al desarrollo social, económico y cultural de la población. Según el plan de ordenamiento territorial,'),
        (0.0648, 'esta estructura se organiza en dos grandes categorías, la estructura ecológica principal y la estructura ecológica complementaria. La estructura ecológica principal, también llamada EEP. Esta es el nivel de mayor prioridad. Su propósito es conservar, mantener'),
        (0.0512, 'o recuperar las funciones ecológicas más importantes del territorio. Es decir, aquellas funciones que permiten que la naturaleza siga prestando servicios fundamentales para la ciudad y sus habitantes.'),
        (0.0614, 'La estructura ecológica principal está conformada por áreas protegidas de carácter nacional, regional, metropolitano y también por áreas protegidas de la sociedad civil. También incluye áreas de interés estratégico como el sistema hidrográfico, ríos, quebradas y sus retiros.'),
        (0.0580, 'El sistema hidrográfico, cerros tutelares y cadenas montañosas y los nodos y enlaces que permiten la conectividad ecológica o los caminos por donde transitan las especies. Un aspecto clave es que la estructura ecológica principal hace parte del suelo de protección del distrito.'),
        (0.0614, 'Esto significa que son zonas donde la urbanización está restringida precisamente porque cumplen funciones ambientales esenciales. En palabras sencillas, son áreas que la ciudad debe cuidar porque sostienen la vida, regula en el agua, protege en el suelo y ayudan a conservar los ecosistemas.'),
        (0.0614, 'La segunda categoría es la estructura ecológica complementaria. O, E, S. Esta tiene un segundo nivel de prioridad, pero también cumple una función muy importante, conectar, reforzar y ampliar los beneficios de la estructura principal.'),
        (0.0580, 'La estructura ecológica complementaria incluye relictos de vegetación, corredores verdes, áreas transformadas y espacios intervenidos que todavía pueden cumplir funciones ambientales importantes. También incorpora zonas prioritarias para la prevención del riesgo,'),
        (0.0546, 'especialmente frente a movimientos en masa inundaciones y avenidas torrenciales. Además, puede incluir áreas importantes para la captura y almacenamiento de carbono, la recarga de acuíferos, el aprovisionamiento de productos forestales y alimentos,'),
        (0.0444, 'los servicios culturales y los nodos complementarios de conectividad ecológica. Dicho de otra manera, la estructura ecológica complementaria ayuda a que los beneficios ambientales lleguen a más lugares de la ciudad,'),
        (0.0546, 'especialmente en territorios donde la relación entre urbanización, ladera, quebradas y riesgo es muy estrecha. Entonces, podemos resumirlo así. La estructura ecológica principal protege los elementos naturales base del territorio, como el río Medellín,'),
        (0.0614, 'las quebradas, los cerros, las áreas protegidas y los suelos de protección. La estructura ecológica complementaria, por su parte, funciona como una red de apoyo, ayuda a conectar espacios verdes, recuperar zonas intervenidas,'),
        (0.0444, 'reducir riesgos, y extender los beneficios de la naturaleza hacia los barrios y comunidades. Comprender la estructura ecológica de Medellín es comprender que la ciudad no está separada de la naturaleza.'),
        (0.0444, 'La ciudad depende del agua, de las montañas, de los suelos y su protección, de la vegetación y de los ecosistemas que las sostienen. Por eso, cuidar la estructura ecológica también es cuidar la vida,'),
        (0.0240, 'la seguridad, la salud y la calidad de vida de quienes habitamos el territorio.'),
    ],
    'm2-riesgo': [
        (0.0771, 'Territorio y gestión del riesgo. En el plan de ordenamiento territorial, la relación entre la geografía natural, laderas, quebradas, tipos de suelos, pendientes y sistemas ecológicos, y la acción humana, urbanización, ocupación del suelo y formas de evitar, es central para comprender la gestión del riesgo y la sostenibilidad ambiental.'),
        (0.0755, 'Estos elementos no actúan de manera aislada. Por el contrario, se condicionan mutuamente. La geografía define límites, oportunidades y restricciones para la ocupación, y las formas de ocupación pueden aumentar, reducir o transformar las condiciones de riesgo existentes. Uno, la geografía como condicionante de la ocupación.'),
        (0.0653, 'La estructura ecológica y las áreas de amenaza y riesgo son los soportes físicos naturales que orientan y condicionan todas las estrategias de intervención en el territorio. Desde esta perspectiva, el pot establece que la ocupación del suelo debe ajustarse a la capacidad de soporte del territorio, especialmente en zonas de ladera, borde urbanos rurales,'),
        (0.0680, 'retiros de quebrada y áreas con restricciones topográficas, geológicas e hidrográficas. Esto implica reconocer que no todos los lugares pueden ocuparse de la misma manera ni con la misma intensidad. Por ello, el modelo de ocupación plantea criterios como densidades de crecientes. En los borde y laderas se promueven menores densidades habitacionales'),
        (0.0611, 'debido a las limitaciones físicas del terreno y a la presencia de amenazas naturales. Urbanismo ecológico. En las zonas de ladera se busca consolidar el híbeta bajo criterios de sostenibilidad ambiental, mejoramiento integral, protección ecológica y densificación moderada, ocupación condicionada.'),
        (0.0407, 'Las intervenciones urbanas deben reconocer las características del suelo, las pendientes, la estabilidad de las laderas, la presencia de quebradas y las condiciones de accesibilidad, servicios e infraestructura.'),
        (0.0660, '2. Las quebradas como infraestructura natural estratégica. Las quebradas son elementos estructurantes del paisaje y de la red de conectividad ecológica. Sin embargo, cuando sus causes, retiros o zonas de influencia son ocupados inadecuadamente, se convierten en escenarios de riesgo,'),
        (0.0667, 'especialmente frente a inundaciones, crecientes súbitas y avenidas torrenciales. Por esta razón, el pot reconoce la importancia de proteger sus áreas de retiro mediante, zonas de retiro. Se definen fajas laterales paralelas a las corrientes que tienen prohibición de edificación. Su función es permitir la dinámica natural de las quebradas,'),
        (0.0606, 'reducir la exposición de la población y servir como fajas de protección frente a amenazas hídricas. Control de la ocupación. La urbanización sobre retiros de quebradas, la modificación de causes, el taponamiento de drenajes o la ocupación de zonas inundables pueden aumentar la amenaza y agravar las condiciones de riesgo.'),
        (0.0576, 'Ecoparques de quebrada. Esta figura permite recuperar ambientalmente las quebradas, proteger el recurso hídrico, restaurar la vegetación, generar espacios públicos y evitar nuevas ocupaciones en zonas ambientalmente sensibles o expuestas a amenaza. Tres.'),
        (0.0455, 'La ladera y los movimientos en masa. Las laderas de Medellín presentan condiciones naturales de inestabilidad asociadas al apendiente, la geología, los suelos, el agua superficial'),
        (0.0788, 'y subterránea y los procesos de transformación del territorio. Estas condiciones pueden agravarse cuando existen formas de ocupación inadecuadas como cortes del terreno sin manejo técnico, llenos inestables, construcciones sobre escombros, ausencia de drenajes, vertimientos de aguas, de forestación o urbanización en zonas de alta pendiente. En este contexto, el pot incorpora la gestión de la amenaza'),
        (0.0697, 'por movimientos en masa entendida como la probabilidad de que ocurran deslizamientos, desprendimientos o desplazamientos de materiales ladera abajo. Para orientar las decisiones de ocupación, estas zonas pueden clasificarse según niveles de amenaza, baja media o alta y según sus condiciones de riesgo con el fin de definir qué tipo de intervenciones pueden permitirse,'),
        (0.0879, 'condicionarse, mitigarse o restringirse. En conclusión, el poto de Medellín busca equilibrar la ocupación humana con las condiciones naturales del territorio. En este sentido, las quebradas y laderas no deben entenderse únicamente como amenazas. Si no también como componentes esenciales de la estructura ecológica. Corredores ambientales, espacios públicos potenciales'),
        (0.0576, 'y soportes para la sostenibilidad urbana. La gestión del riesgo entonces no consiste solo en responder a emergencias o identificar zonas peligrosas. También implica ordenar mejor el territorio, reconocer sus límites naturales, evitar nuevas ocupaciones en áreas expuestas'),
        (0.0219, 'y reducir progresivamente las condiciones de vulnerabilidad, socio-económicas de las poblaciones más expuestas.'),
    ],
    'm2-tensiones': [
        (0.0500, 'Tensiones territoriales en las laderas y el borde urbano rural de Medellín. Cuando hablamos de las laderas y del borde urbano rural de Medellín, no estamos hablando solamente de un lugar ubicado entre la ciudad y el campo.'),
        (0.0800, 'Estamos hablando de territorios vivos, complejos, donde se cruzan distintas formas de evitar. Los ecosistemas, el riesgo de desastres, la desigualdad, la historia de las migraciones y el conflicto armado y las formas en que diferentes actores disputan el uso y ocupación del suelo. A estas situaciones las podemos llamar tensiones territoriales.'),
        (0.0500, 'Una primera tensión aparece entre la urbanización y el riesgo de desastres. En muchas laderas, las familias han construido sus viviendas cerca de quebradas, en zonas de alta pendiente, o en áreas expuestas a movimientos en masa,'),
        (0.0467, 'inundaciones y avenidas torrenciales. También existen viviendas levantadas sobre rellenos inestables, escombreras o terrenos modificados sin las condiciones técnicas adecuadas.'),
        (0.0400, 'Esto no significa que las comunidades quieran vivir en riesgo. Muchas veces significa que la ciudad no ha ofrecido suficientes alternativas seguras, dignas y accesibles para evitar.'),
        (0.0467, 'Una segunda tensión tiene que ver con el control territorial y la informalidad. En algunos sectores, actores ilegales se aprovechan de la necesidad de vivienda. Venden lotes de manera irregular, controlan el acceso a materiales de construcción'),
        (0.0400, 'o intervienen en la conexión informal de servicios básicos. En otros casos, las comunidades deben pagar cobros ilegales por agua, energía, transporte, basuras o seguridad.'),
        (0.0700, 'Así el territorio no solo se ocupa, también se controla, se negocia y se disputa. Una tercera tensión está relacionada con el desplazamiento forzado y la revictimización. Las laderas de Medellín han sido, al mismo tiempo, lugares de llegada y de expulsión de población desplazada.'),
        (0.0533, 'Personas que huyen de la violencia rural o intraurbana terminan ubicándose en barrios donde también existen condiciones de precariedad, control armado o amenaza de nuevos desplazamientos. Esto genera una situación profundamente injusta.'),
        (0.0633, 'Quienes buscan protección pueden quedar nuevamente expuestos a riesgos sociales, económicos y ambientales. Una cuarta tensión se expresa en la precariedad del híbitat y el déficit de servicios. En varios sectores de desarrollo incompleto hay dificultades de acceso a espacio público, equipamientos de salud,'),
        (0.0600, 'educación, saneamiento básico, movilidad segura y servicios públicos domiciliarios. También existen problemas de tenencia de la tierra. La falta de títulos o condiciones jurídicas claras limita la inversión pública y dificulta los procesos de mejoramiento integral de la híbitat.'),
        (0.0433, 'Una quinta tensión está relacionada con los conflictos de uso del suelo. Por un lado, existe una necesidad real de vivienda. Por otro, hay suelos que cumplen funciones ambientales fundamentales.'),
        (0.0700, 'Protejen quebradas, conservan vegetación, conectan ecosistemas, regulan el agua y ayudan a reducir riesgos. Cuando la presión por ocupar el suelo avanza sobre áreas de protección se afectan la estructura ecológica principal. Los retiros de quebrada, los cerros tutelares y otros espacios clave para la sostenibilidad de la ciudad.'),
        (0.0900, 'Además, actividades como la minería, en el caso específico de altavista y san cristóbal. Las quemas de vegetación, el manejo inadecuado de residuos o la ocupación de zonas de protección pueden aumentar los conflictos ambientales y el deterioro del territorio. En resumen, las laderas de Medellín concentran múltiples tensiones, riesgo físico, desigualdad social, informalidad urbana, presión ambiental,'),
        (0.0733, 'déficit de servicios y disputas por el control del territorio. Por eso, comprender el riesgo no es solo mirar un mapa de amenazas. También es preguntarnos, ¿quiénes viven allí? ¿Por qué llegaron a ese lugar? ¿Qué condiciones tienen para protegerse? ¿Qué decisiones públicas han faltado? ¿Qué actores intervienen en el territorio?'),
        (0.0800, '¿Y cómo se puede construir una ciudad más segura, justa y ambientalmente responsable? Hablar detenciones territoriales es reconocer que el riesgo no se produce solamente por la lluvia, la pendiente o la quebrada. El riesgo también se construye socialmente, a partir de decisiones, desigualdades, ausencias, controles y formas de ocupación del suelo.'),
        (0.0434, 'Comprender esto es el primer paso para transformar nuestro territorio. Tómate un café o una deliciosa agua panela y responde. ¿Cómo transformamos estas tensiones?'),
    ],
    'm3-intro': [
        (0.0412, 'Módulo 2. Entender el territorio donde vivimos. Bienvenidas y bienvenidos al segundo módulo de este curso corto en comprensión del riesgo. Este módulo tiene como objetivo reconocer que es el borde urbano rural'),
        (0.0725, 'y por qué allí se concentran decisiones claves sobre riesgo, vivienda, ambiente y calidad de vida. Cuando hablamos del borde urbano rural, nos referimos a una zona viva en transformación que conjuga dos dinámicas generales que interactúan, las ruralidades o formas rurales de evitar y la urbanización. El borde urbano rural es una zona de transición entre el campo y la ciudad. Por ello es necesario una planificación y gestión diferenciada,'),
        (0.0435, 'pues se combina riesgo, híbitat, formas de evitar, soporte urbano, ecosistemas estratégicos, protección del patrimonio y producción rural. En esencia es necesario planificar las formas de ocupar el suelo y las decisiones sobre cómo crece la ciudad.'),
        (0.0725, 'Por este tipo de razones, se considera un área de intervención estratégica. En estos territorios se concentran muchas preguntas importantes. ¿Qué tiene que ver esta unidad de planificación con mi vivienda y mi híbitat? ¿Cuáles son las causas principales de las emergencias o desastres en el territorio? ¿Cuáles son los impedimentos para la baja ejecución del mejoramiento integral? Para comprender el riesgo es necesario conocer el territorio,'),
        (0.0728, 'pero también saber diferenciar cuatro ideas básicas. La amenaza es un fenómeno que puede causar daño como un movimiento en masa, una avenida torrencial o una inundación. La exposición se refiere a las personas, viviendas, vías o equipamientos que están ubicados en una zona donde puede ocurrir esa amenaza. La vulnerabilidad tiene que ver con qué tan frágiles o preparados estamos frente a ese posible daño.'),
        (0.0493, 'Y el riesgo aparece cuando se combinan amenaza, exposición y vulnerabilidad. Muchos de nosotros hemos convivido con el riesgo como única alternativa para evitar la ciudad. Pero al ser ciudadano, si ciudadanas, significa que no debemos acostumbrarnos a él ni aceptarlo como algo normal.'),
        (0.0431, 'Significa reconocerlo, hablarlo, entenderlo y participar en las decisiones que pueden reducirlo. No sólo necesitamos saber de estudios de riesgo, necesitamos conocer el plan de ordenamiento territorial e incidir en su construcción y actualización.'),
        (0.0413, 'Hoy, además, el cambio climático y la variabilidad climática hacen que las lluvias intensas, los periodos secos y los cambios en el clima se sientan con más fuerza en la vida diaria. Por eso, comprender el territorio es también comprender cómo cuidarnos mejor.'),
        (0.0809, 'Este módulo nos invita a mirar el lugar que habitamos con otros ojos. No sólo como un barrio o una ladera, sino como un territorio con historia, naturaleza, riesgos, capacidades y decisiones compartidas. Módulo 3, la construcción del riesgo y el cambio climático. Bienvenidas y bienvenidos. En este módulo vamos a conversar sobre una idea muy importante.'),
        (0.0430, 'El riesgo de desastres y su relación con los efectos del cambio climático. Este no aparece solamente porque exista una amenaza natural, como una lluvia fuerte, un deslizamiento, una inundación o una avenida torrencial.'),
        (0.0745, 'El riesgo también se construye a partir de las formas de evitar el territorio, las prácticas constructivas, la historia de vida de sus primeros habitantes, las condiciones de las infraestructuras vitales, las condiciones socioeconómicas y las desigualdades sociales. También, el riesgo y su gestión tiene que ver con la organización comunitaria, sus capacidades de agencia y las acciones o inacciones institucionales.'),
        (0.0409, 'Por eso, durante este recorrido vamos a diferenciar conceptos clave como amenaza, vulnerabilidad, capacidades, exposición y riesgo. También hablaremos del riesgo como una construcción social,'),
        (0.0700, 'es decir, como el resultado de procesos históricos, económicos, ambientales y territoriales, que pueden aumentar o reducir la posibilidad de que una comunidad sufradaños. Este módulo también nos invita a mirar el riesgo desde la vida cotidiana. Nos preguntaremos qué nos dicen los indicadores de calidad de vida sobre las comunas, uno, tres y ocho, que está pasando con la población,'),
        (0.0554, 'cómo influyen las condiciones sociales, económicas y demográficas en la manera como una comunidad en frente a un desastre. Además, abordaremos el concepto de vulnerabilidad, no como una debilidad de las personas, sino como una condición social y territorial que puede cambiar. Una vivienda frágil, la falta de drenajes, los bajos ingresos,'),
        (0.0529, 'las dificultades de acceso a servicios, el cuidado de niños, personas mayores o personas con discapacidad, y la ausencia de canales de comunicación barrial pueden hacer que una amenaza tenga impactos más graves. Finalmente, hablaremos del cambio climático y la variabilidad climática desde el lenguaje cotidiano.'),
        (0.0461, 'Porque muchas veces estos conceptos se reconocen en frases simples, hace más calor. Las lluvias ya no son como antes. Los aguaceros son más fuertes. O, el clima está loco. Estas percepciones son importantes,'),
        (0.0629, 'porque conectan el conocimiento técnico con la experiencia diaria. La invitación en este módulo es a observar, preguntar y reflexionar. ¿Cómo se construye el riesgo en nuestro barrio? ¿Qué condiciones aumentan la vulnerabilidad? ¿Qué capacidades comunitarias existen para transformar el territorio? ¿Y cómo podemos comprender mejor los cambios del clima'),
        (0.0372, 'desde nuestra propia experiencia? Comencemos este recorrido con un buen café.'),
    ],
    'm3-clima': [
        (0.0618, 'Cambioclimático y variabilidad climática en el lenguaje cotidiano. Cuando hablamos de cambio climático y variabilidad climática, muchas veces pensamos en conceptos científicos, datos, gráficas o informes técnicos. Pero en la vida cotidiana, la gente suele decirlo de otra manera. Hace más calor.'),
        (0.0416, 'Las lluvias ya no son como antes. El clima está loco, llueve cuando no debería. Los aguaceros están más fuertes. Y esas frases son importantes, porque muestran cómo las personas entienden el clima desde su propia experiencia,'),
        (0.0677, 'desde lo que pasa en su casa, en su barrio, en la quebrada cercana, en la movilidad, en la salud, en el trabajo o en la seguridad de su vivienda. Entonces, empecemos por una diferencia básica. ¿Qué es la variabilidad climática? La variabilidad climática se puede entender como los cambios normales, ofrecuentes del clima en períodos cortos o medianos.'),
        (0.0496, 'Por ejemplo, temporadas más lluviosas, meses más secos, años con más calor o días con lluvias intensas. Es decir, son como los altibajos del clima. Exactamente. No todos los años llueve igual, no todos los meses son igual de secos,'),
        (0.0752, 'y no todas las temporadas tienen la misma temperatura. Esa variación hace parte del comportamiento del clima. Y entonces, ¿qué es el cambio climático? El cambio climático es una transformación más profunda y sostenida en el tiempo. No se trata sólo de que un día haga calor o de que una semana llueva mucho. Se refiere a cambios más duraderos que pueden modificar los promedios del clima,'),
        (0.0464, 'intensificar eventos extremos y alterar patrones que antes eran más conocidos. O sea, la variabilidad climática son cambios que ocurren entre días, meses o años, mientras que el cambio climático es una transformación más larga'),
        (0.0580, 'que puede hacer que esos cambios sean más frecuentes, intensos o difíciles de predecir. Así es. Y esto es importante porque, como señalan estudios sobre percepción pública del clima, muchas personas no reconocen el cambio climático primero como un problema de gases de efecto invernadero o estadísticas globales,'),
        (0.0561, 'sino como señales cercanas. Más calor en la casa, pérdida de fuentes de agua, lluvias más fuertes, daños en caminos, colapso del sistema de alcantarillado, enfermedades o afectaciones en los cultivos. En un barrio de ladera, por ejemplo, una lluvia intensa no es sólo mal tiempo.'),
        (0.0689, 'Claro, en territorios de ladera una lluvia fuerte puede relacionarse con escorrentías, saturación del suelo, crecientes de quebradas, movimientos en masa o avenidas torrenciales. Y ahí el clima se conecta con la vivienda y los servicios públicos, con el manejo del agua, con las prácticas constructivas, los usos del suelo, la gestión de residuos sólidos y, en general,'),
        (0.0445, 'con las condiciones de riesgo. Por eso, desde el conocimiento del riesgo, es útil explicar estos conceptos desde ejemplos territoriales y no sólo desde definiciones abstractas. También pasa algo común. Muchas personas mezclan palabras como'),
        (0.0691, 'cambio climático, calentamiento global, variabilidad climática y mal tiempo. Sí, y no significan exactamente lo mismo. Por ejemplo, calentamiento global suele asociarse más con el aumento de la temperatura. En cambio, cambio climático permite hablar también de lluvias, sequías, tormentas, cambios en los ciclos del agua y eventos extremos.'),
        (0.0698, 'Por eso, para comunicar mejor, conviene partir de lo que la gente vive. El calor en las viviendas, las lluvias que cambian, las quebradas que crecen, los caminos que se deterioran, o las zonas donde se presentan deslizamientos. También es necesario avanzar en aspectos más complejos como los bioindicadores o especies vegetales,'),
        (0.0694, 'ongos o animales susceptibles a los cambios en el clima. Entonces, podríamos resumirlo así. La variabilidad climática son los cambios y altibajos del clima que se presentan entre días, meses o años. Y el cambio climático es una transformación más duradera que puede hacer que esos cambios sean más frecuentes, intensos o difíciles de predecir.'),
        (0.0746, 'En la vida diaria, ambos se sienten cuando cambian las lluvias, aumenta el calor, se intensifican los aguaceros o crecen las condiciones que pueden favorecer deslizamientos, inundaciones y avenidas torrenciales. En territorios como el borde urbano rural nororiental de Medellín, hablar del clima es hablar también de la seguridad alimentaria, salud pública ambiental, renaturalización y regeneración,'),
        (0.0616, 'la gestión de la escorrentía superficial y en general de la adaptación al cambio climático. Se necesita reducir las actividades generadoras de gases efecto invernadero que debilitan la atmósfera, pero es fundamental la adaptación ya que esta debe responder a dos realidades. Prepararse para los eventos actuales, lluvias intensas,'),
        (0.0857, 'sequías o las de calor o deslizamientos asociados a temporadas críticas y al mismo tiempo anticipar escenarios futuros donde esos eventos pueden ser más frecuentes, intensos o impredesibles. En síntesis, la adaptación permite pasar de soportar los impactos del clima a preparar el territorio y las comunidades para vivir mejor en un clima cambiante.'),
    ],
    'm4-intro': [
        (0.0418, 'Módulo 2. Entender el territorio donde vivimos. Bienvenidas y bienvenidos al segundo módulo de este curso corto en comprensión del riesgo. Este módulo tiene como objetivo reconocer qué es el borde urbano rural, y por qué allí se concentran decisiones claves sobre riesgo,'),
        (0.0407, 'vivienda, ambiente y calidad de vida. Cuando hablamos del borde urbano rural, nos referimos a una zona viva en transformación que conjuga dos dinámicas generales que interactúan, las ruralidades o formas rurales de evitar y la urbanización. El borde urbano rural es una zona de transición'),
        (0.0586, 'entre el campo y la ciudad. Por ello es necesario una planificación y gestión diferenciada, pues se combina riesgo, híbitad, formas de evitar, soporte urbano, ecosistemas estratégicos, protección del patrimonio y producción rural. En esencia es necesario planificar las formas de ocupar el suelo y las decisiones sobre cómo crece la ciudad. Por este tipo de razones se considera un área de intervención estratégica.'),
        (0.0589, 'En estos territorios se concentran muchas preguntas importantes. ¿Qué tiene que ver esta unidad de planificación con mi vivienda y mi híbitat? ¿Cuáles son las causas principales de las emergencias o desastres en el territorio? ¿Cuáles son los impedimentos para la baja ejecución del mejoramiento integral? Para comprender el riesgo es necesario conocer el territorio, pero también saber diferenciar cuatro ideas básicas.'),
        (0.0609, 'La amenaza es un fenómeno que puede causar daño como un movimiento en masa, una avenida torrencial o una inundación. La exposición se refiere a las personas, viviendas, vías o equipamientos que están ubicados en una zona donde puede ocurrir esa amenaza. La vulnerabilidad tiene que ver con qué tan frágiles o preparados estamos frente a ese posible daño. Y el riesgo aparece cuando se combinan amenaza, exposición'),
        (0.0563, 'y vulnerabilidad. Muchos de nosotros hemos convivido con el riesgo como única alternativa para evitar la ciudad. Pero al ser ciudadanos y ciudadanas significa que no debemos acostumbrarnos a él ni aceptarlo como algo normal. Significa reconocerlo, hablarlo, entenderlo y participar en las decisiones que pueden reducirlo. No sólo necesitamos saber de estudios de riesgo,'),
        (0.0563, 'necesitamos conocer el plan de ordenamiento territorial e incidir en su construcción y actualización. Hoy además, el cambio climático y la variabilidad climática hacen que las lluvias intensas, los periodos secos y los cambios en el clima se sientan con más fuerza en la vida diaria. Por eso, comprender el territorio es también comprender cómo cuidarnos mejor. Este módulo nos invita a mirar el lugar que habitamos'),
        (0.0464, 'con otros ojos. No sólo como un barrio o una ladera, sino como un territorio con historia, naturaleza, riesgos, capacidades y decisiones compartidas. Módulo 3. La construcción del riesgo y el cambio climático.'),
        (0.0483, 'Bienvenidas y bienvenidos. En este módulo vamos a conversar sobre una idea muy importante. El riesgo de desastres y su relación con los efectos del cambio climático. Este no aparece solamente porque exista una amenaza natural como una lluvia fuerte, un deslizamiento, una inundación'),
        (0.0559, 'o una avenida torrencial. El riesgo también se construye a partir de las formas de habitar el territorio. Las prácticas constructivas. La historia de vida de sus primeros habitantes. Las condiciones de las infraestructuras vitales. Las condiciones socioeconómicas y las desigualdades sociales. También, el riesgo y su gestión tiene que ver con la organización comunitaria,'),
        (0.0458, 'sus capacidades de agencia y las acciones o inacciones institucionales. Por eso, durante este recorrido, vamos a diferenciar conceptos clave como amenaza, vulnerabilidad, capacidades, exposición y riesgo. También hablaremos del riesgo como una construcción social.'),
        (0.0577, 'Es decir, como el resultado de procesos históricos, económicos, ambientales y territoriales que pueden aumentar o reducir la posibilidad de que una comunidad sufradaños. Este módulo también nos invita a mirar el riesgo desde la vida cotidiana. Nos preguntaremos qué nos dicen los indicadores de calidad de vida sobre las comunas 1, 3 y 8. ¿Qué está pasando con la población?'),
        (0.0518, '¿Cómo influyen las condiciones sociales, económicas y demográficas en la manera como una comunidad en frente a un desastre? Además, abordaremos el concepto de vulnerabilidad. No como una debilidad de las personas, sino como una condición social y territorial que puede cambiar. Una vivienda frágil, la falta de drenajes, los bajos ingresos, las dificultades de acceso a servicios,'),
        (0.0487, 'el cuidado de niños, personas mayores o personas con discapacidad y la ausencia de canales de comunicación barrial pueden hacer que una amenaza tenga impactos más graves. Finalmente, hablaremos del cambio climático y la variabilidad climática desde el lenguaje cotidiano. Porque muchas veces estos conceptos se reconocen en frases simples,'),
        (0.0472, 'hace más calor. Las lluvias ya no son como antes. Los aguaceros son más fuertes o el clima está loco. Estas percepciones son importantes porque conectan el conocimiento técnico con la experiencia diaria. La invitación en este módulo es a observar,'),
        (0.0693, 'preguntar y reflexionar. ¿Cómo se construye el riesgo en nuestro barrio? ¿Qué condiciones aumentan la vulnerabilidad? ¿Qué capacidades comunitarias existen para transformar el territorio? ¿Y cómo podemos comprender mejor los cambios del clima desde nuestra propia experiencia? Comencemos este recorrido con un buen café. Módulo 4. Conocimientos, saberes y herramientas para la gestión del riesgo.'),
        (0.0510, 'Bienvenidas y bienvenidos al último módulo de este curso corto en conocimiento del riesgo. En este módulo hablaremos de una capacidad muy importante. Observar el territorio. Cuando una persona nota que una grieta creció, que un muro se inclinó, que apareció agua donde antes no había, o que una puerta ya no sierra bien, está identificando posibles señales de alerta.'),
        (0.0542, 'La gestión del riesgo no se construye solo con estudios técnicos. También necesita de los saberes comunitarios, de la memoria barrial y del monitoreo cotidiano. Observar, registrar y comunicar cambios a tiempo puede ayudar a prevenir emergencias. Durante este módulo, reconoceremos señales en la vivienda, en el terreno, en las vías y en el entorno. También exploraremos herramientas virtuales'),
        (0.0503, 'como el geoportal de Joe Assards, la página web diseñada para la comunidad y los Storymaps que permiten comprender y compartir mejor la información sobre el territorio. La invitación es a preguntarnos. ¿Qué nos está diciendo el lugar que habitamos? Escuchar esas señales, compartirlas y actuar de manera organizada es una forma de cuidar la vida, la vivienda y la comunidad.'),
    ],
}

# Build replacement text for each lesson id
for lid, segments in new_transcripts.items():
    # Find the existing transcript block and replace it
    # Pattern: transcript: [ ... ]
    # We'll match from 'transcript: [' to the next '{' that starts the next lesson
    # Better approach: match the entire transcript array content
    
    # Build new JS array text
    lines = ['transcript: [']
    for pct, text in segments:
        escaped = text.replace("'", "\\'").replace('ó', 'ó').replace('í', 'í').replace('á', 'á').replace('é', 'é').replace('ú', 'ú').replace('ñ', 'ñ')
        # Actually, we need the original accented chars. Let's just use raw text.
        lines.append(f"  {{ pct: {pct:.4f}, text: '{text}' }},")
    lines.append('],')
    new_block = '\n          '.join(lines)
    
    # Find the old transcript block - from 'transcript: [' to the next '],' that closes it
    # Use regex to find transcript: [ ... ],
    pattern = rf"({lid}',\s*\n\s*transcript: )\[.*?\]"
    
    # We need to be more specific. Let me find by unique context around each transcript
    # Actually, let me just match the transcript block by lesson id context
    
    old_pattern = lid + "',\n"
    idx = html.find(old_pattern)
    if idx > 0:
        # Find 'transcript: [' after this
        t_idx = html.find("transcript: [", idx)
        if t_idx > 0:
            # Find the closing '],' of the transcript array
            # Count brackets to find the match
            start = t_idx + len("transcript: [")
            depth = 1
            pos = start
            while depth > 0 and pos < len(html):
                if html[pos] == '[':
                    depth += 1
                elif html[pos] == ']':
                    depth -= 1
                pos += 1
            end = pos  # position after ']'
            
            # Now replace html[t_idx:end+1] with new_block
            html = html[:t_idx] + new_block + html[end:]

with open(r'E:\Trabajo\1-OpenCode\web-page\curso\index.html', 'w', encoding='utf-8') as f:
    f.write(html)

print('Done! Transcripts replaced.')
